language: node_js
node_js:
  - "7"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database mydiary;' -U postgres  
script:
  - npm test
after_success:
-  npm run coverage